/**
 * This file was auto-generated from the OpenAPI schema.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update these types, edit test/fixtures/openapi.json and run:
 *   npm run sync-types
 */

import { z } from 'zod';

export type Role = 'member' | 'moderator' | 'admin'

export const RoleSchema = z.enum(['member', 'moderator', 'admin'])

export type MembershipTier = 'free' | 'standard' | 'pro'

export const MembershipTierSchema = z.enum(['free', 'standard', 'pro'])

export const WebhookEventStatusSchema = z.enum(['success', 'failed', 'pending'])

export const WebhookEventTypeSchema = z.enum(['membership.created', 'membership.renewed', 'membership.expired', 'tier.upgraded', 'policy.updated'])

export const WebhookPayloadSummarySchema = z.object({
  network: z.string().optional(),
  txHash: z.string().optional(),
  tier: z.string().optional(),
  reason: z.string().optional(),
})

export const WebhookEventLogSchema = z.object({
  id: z.string(),
  eventType: WebhookEventTypeSchema,
  status: WebhookEventStatusSchema,
  timestamp: z.string(),
  affectedIdentifier: z.string(),
  payloadSummary: WebhookPayloadSummarySchema,
})

export interface Community {
  id: string
  name: string
  description?: string
  tiers: MembershipTier[]
}

export const CommunitySchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional(),
  tiers: z.array(MembershipTierSchema),
})

export interface Membership {
  address: string
  tier: MembershipTier
  active: boolean
  expiresAt?: string
}

export const MembershipSchema = z.object({
  address: z.string(),
  tier: MembershipTierSchema,
  active: z.boolean(),
  expiresAt: z.string().optional(),
})

export interface MemberProfile {
  address: string
  displayName?: string
  bio?: string
  badges: string[]
}

export const MemberProfileSchema = z.object({
  address: z.string(),
  displayName: z.string().optional(),
  bio: z.string().optional(),
  badges: z.array(z.string()),
})

export interface Session {
  address?: string
  roles: Role[]
  membership?: Membership
  community?: Community
}

export const SessionSchema = z.object({
  address: z.string().optional(),
  roles: z.array(RoleSchema),
  membership: MembershipSchema.optional(),
  community: CommunitySchema.optional(),
})

export interface ResourceContentBlock {
  type: string
  body?: string
  url?: string
  title?: string
  level?: string
}

export const ResourceContentBlockSchema = z.object({
  type: z.string(),
  body: z.string().optional(),
  url: z.string().optional(),
  title: z.string().optional(),
  level: z.string().optional(),
})

export interface Resource {
  id: string
  title: string
  description?: string
  minTier?: MembershipTier
  roles?: Role[]
  content?: ResourceContentBlock[]
}

export const ResourceSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().optional(),
  minTier: MembershipTierSchema.optional(),
  roles: z.array(RoleSchema).optional(),
  content: z.array(ResourceContentBlockSchema).optional(),
})

export interface AccessPolicy {
  resourceId: string
  minTier?: MembershipTier
  roles?: Role[]
}

export const AccessPolicySchema = z.object({
  resourceId: z.string(),
  minTier: MembershipTierSchema.optional(),
  roles: z.array(RoleSchema).optional(),
})

export interface MemberRow {
  address: string
  roles: Role[]
  tier: MembershipTier
  active: boolean
}

export const MemberRowSchema = z.object({
  address: z.string(),
  roles: z.array(RoleSchema),
  tier: MembershipTierSchema,
  active: z.boolean(),
})

export const ApiErrorBodySchema = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
  message: z.string().optional(),
  details: z.record(z.unknown()).optional(),
})

export interface SiweAuthSession {
  isAuthenticated: true
  token: string
  address: string
  expiresAt: string
}

export const SiweAuthSessionSchema = z.object({
  isAuthenticated: z.literal(true),
  token: z.string(),
  address: z.string(),
  expiresAt: z.string(),
})

export const WalletVerificationSchema = z.object({
  verified: z.boolean(),
  method: z.string().optional(),
  checkedAt: z.string(),
})

export type WebhookEventStatus = 'success' | 'failed' | 'pending';

export type WebhookEventType = 
  | 'membership.created' 
  | 'membership.renewed' 
  | 'membership.expired' 
  | 'tier.upgraded' 
  | 'policy.updated';

export interface WebhookEventLog {
  id: string;
  eventType: WebhookEventType;
  status: WebhookEventStatus;
  timestamp: string;
  affectedIdentifier: string; // Wallet address or Resource ID
  payloadSummary: {
    network?: string;
    txHash?: string;
    tier?: string;
    reason?: string;
  };
}

export interface WalletVerification {
  verified: boolean
  method?: string
  checkedAt: string
}

export interface ApiErrorBody {
  code?: string
  error?: string
  message?: string
  details?: Record<string, unknown>
}

// ── Access Decision (cached per wallet + resource) ───────────────────────────

/**
 * Result of an access check for a specific resource.
 * This is the value stored in the route-level access cache.
 * Only safe display metadata is included — never sensitive tokens.
 */
export interface AccessDecision {
  /** Whether access is granted */
  allowed: boolean
  /** Human-readable reason for the decision (safe for display) */
  reason: string
  /** ISO timestamp of when the check was performed */
  checkedAt: string
}

// ── Client-side State Types ──────────────────────────────────────────────────

/**
 * Distinct states of the admin authentication session.
 *
 * - disconnected   — no wallet connected
 * - connected      — wallet connected, but SIWE sign-in not yet performed
 * - authenticating — SIWE signing flow is in-flight
 * - authenticated  — valid, non-expired session token is held
 * - expired        — a session was held but the token has since expired (or
 *                    the backend rejected it with 401); re-auth is required
 */
export type AdminSessionStatus =
  | 'disconnected'
  | 'connected'
  | 'authenticating'
  | 'authenticated'
  | 'expired'

/**
 * Union of authenticated / unauthenticated states for the SIWE context.
 */
export type SiweAuthState =
  | SiweAuthSession
  | { isAuthenticated: false }

// ── Backend raw types (guildpass-core response shapes) ───────────────────────
// These are the shapes returned by /v1/* endpoints. The live API client maps
// them into the frontend types above. Fields are optional because backend
// versions may use snake_case or camelCase, and this mapping handles both.

export interface BackendMember {
  address?: string
  wallet_address?: string
  tier?: MembershipTier
  membership_tier?: MembershipTier
  active?: boolean
  is_active?: boolean
  expiresAt?: string
  expires_at?: string
  roles?: Role[]
  // Profile fields (returned by /v1/members/:address/profile)
  displayName?: string
  display_name?: string
  username?: string
  bio?: string
  badges?: string[]
}

export interface BackendResource {
  id: string
  title?: string
  name?: string
  description?: string
  minTier?: MembershipTier
  min_tier?: MembershipTier
  roles?: Role[]
  content?: ResourceContentBlock[]
}

export interface BackendPolicy {
  resourceId?: string
  resource_id?: string
  minTier?: MembershipTier
  min_tier?: MembershipTier
  roles?: Role[]
}

export interface BackendSession {
  address?: string
  wallet_address?: string
  roles?: Role[]
  membership?: Partial<BackendMember>
  community?: {
    id: string
    name: string
    description?: string
    tiers?: MembershipTier[]
  }
}

// ── API Interface ─────────────────────────────────────────────────────────────

/**
 * Read-only member and resource queries.
 * No SIWE token is required for these operations.
 */
export interface MemberAccessApi {
  // ── Read-only (no auth token required) ──────────────────────────────────
  getSession(): Promise<Session>
  getCommunity(): Promise<Community>
  getMembership(address: string): Promise<Membership | null>
  verifyWallet(address: string): Promise<WalletVerification>
  getProfile(address: string): Promise<MemberProfile | null>
  listMembers(): Promise<MemberRow[]>
  listResources(): Promise<Resource[]>
  listPolicies(): Promise<AccessPolicy[]>
  getResource(id: string): Promise<Resource | null>
  getPolicy(resourceId: string): Promise<AccessPolicy | null>
}

/**
 * Authenticated admin queries and mutations.
 * These methods require a valid SIWE token context.
 */
export interface AdminAccessApi {
  // ── Admin queries & mutations (require a valid SIWE token context) ────────
  listWebhookEvents(): Promise<WebhookEventLog[]>
  assignRole(address: string, role: Role): Promise<void>
  removeRole(address: string, role: Role): Promise<void>
  updatePolicy(policy: AccessPolicy): Promise<void>
}

/**
 * SIWE authentication endpoints.
 */
export interface SiweAuthApi {
  // ── SIWE authentication endpoints ────────────────────────────────────────
  /** Fetch a one-time nonce for the given address to include in the SIWE message. */
  getNonce(address: string): Promise<string>
  /**
   * Submit a signed EIP-4361 message and receive an authenticated session
   * token. The backend verifies the signature and returns a short-lived token.
   */
  siweVerify(message: string, signature: string): Promise<SiweAuthSession>
  /** Invalidate the current server-side session (no-op for stateless JWTs). */
  siweLogout(token: string): Promise<void>
  verifyWallet(address: string): Promise<WalletVerification>
}

/**
 * Composed client-side API contract.
 *
 * Built from {@link MemberAccessApi}, {@link AdminAccessApi}, and
 * {@link SiweAuthApi} so each surface has a single, unambiguous responsibility
 * and implementations cannot drift between duplicated declarations.
 */
export type AccessApi = MemberAccessApi & AdminAccessApi & SiweAuthApi
